### ISSUE TITLE
import pnutpy fails with pythonista

### ISSUE THREAD

**Issue by spacenerdmo** [pnut-api/PNUTpy#13]
The latest PNUTpy package fails to load with a ModuleNotFoundError: No module named 'winreg'

**Comment by spacenerdmo** [comment]
```
>>> import pnutpy
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/76A4FBFD-E0FD-4E5C-900F-A023834D092E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/six.py", line 127, in __getattr__
    _module = self._resolve()
  File "/var/containers/Bundle/Application/76A4FBFD-E0FD-4E5C-900F-A023834D092E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/six.py", line 111, in _resolve
    return _import_module(self.mod)
  File "/var/containers/Bundle/Application/76A4FBFD-E0FD-4E5C-900F-A023834D092E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/six.py", line 78, in _import_module
    __import__(name)
ModuleNotFoundError: No module named 'winreg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/mobile/Containers/Shared/AppGroup/CE699449-B3FA-4D6E-8596-EBC607A8C972/Pythonista3/Documents/site-packages/pnutpy/__init__.py", line 12, in <module>
    from .models import User, Post, Interaction, Token
  File "/private/var/mobile/Containers/Shared/AppGroup/CE699449-B3FA-4D6E-8596-EBC607A8C972/Pythonista3/Documents/site-packages/pnutpy/models.py", line 7, in <module>
    from dateutil.parser import parse
  File "/private/var/mobile/Containers/Shared/AppGroup/CE699449-B3FA-4D6E-8596-EBC607A8C972/Pythonista3/Documents/site-packages/dateutil/parser.py", line 17, in <module>
    from . import tz
  File "/private/var/mobile/Containers/Shared/AppGroup/CE699449-B3FA-4D6E-8596-EBC607A8C972/Pythonista3/Documents/site-packages/dateutil/tz.py", line 19, in <module>
    from dateutil.tzwin import tzwin, tzwinlocal
  File "/private/var/mobile/Containers/Shared/AppGroup/CE699449-B3FA-4D6E-8596-EBC607A8C972/Pythonista3/Documents/site-packages/dateutil/tzwin.py", line 26, in <module>
    TZKEYNAME = _settzkeyname()
  File "/private/var/mobile/Containers/Shared/AppGroup/CE699449-B3FA-4D6E-8596-EBC607A8C972/Pythonista3/Documents/site-packages/dateutil/tzwin.py", line 17, in _settzkeyname
    handle = winreg.ConnectRegistry(None, winreg.HKEY_LOCAL_MACHINE)
  File "/var/containers/Bundle/Application/76A4FBFD-E0FD-4E5C-900F-A023834D092E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/six.py", line 129, in __getattr__
    raise AttributeError(attr)
AttributeError: ConnectRegistry
```

**Comment by spacenerdmo** [comment]
It appears that the bundled version of six is causing the mischief.  Work around tested includes installing the updated version of six using `pip install` then installing pnutpy.
